### ISSUE TITLE
PROGRAM MILESTONE: Translator Release Process is codified and accepted by all teams.

### ISSUE THREAD

**Issue by mmersmann** [ranking-agent/ranking-agent.github.io#18]
Teams are expected to adhere to the [NCATS ITRB Standard CI/CD Policy](https://docs.google.com/document/d/1DEHrRH-euvYCO8PrF4eyQjlOVp63mRFx99YvKYIjGR8/edit).

[NCATS ITRB Tech Stack and Deployment Process Slide Deck](https://docs.google.com/presentation/u/3/d/1vWwopSPWFT329r877LNBikpAGEYa2UZR/edit?usp=drive_web&ouid=107543607682508464570&rtpof=true)

**Comment by mmersmann** [comment]
**Next Step:** To be reviewed in full and discussed with Steve.

**Comment by mmersmann** [comment]
**Action:** @patrickkwang to review policy and talk to Mark about any concerns.

**Comment by mmersmann** [comment]
**Next Steps:**
1. ITRB setting up meetings with individual teams (week of May 10). Patrick and others will address CI/CD concerns at that time.

**Comment by mmersmann** [comment]
Patrick, Steve, Yaphet, Chuck, and PJ met with NCATS ITRB on 5/13 to discuss deployment and collect requirements. See Steve's notes [here](https://docs.google.com/document/d/1Gf3cVRGB3MszfYqV9FONdKT4QnOUTwQCNfBJSuRNDxA/edit?ts=60999094).

**Next Steps:**
1. NCATS to set up dedicated Slack channel to continue conversations.
2. Bi-weekly meetings to be held.

**Comment by mmersmann** [comment]
Work proceeding asynchronously via #devops-sri-ranking Slack channel on Translator workspace.

**Comment by richakanwar13** [comment]
Complete.
