### ISSUE TITLE
PROGRAM MILESTONE: Automated Testing Plan

### ISSUE THREAD

**Issue by mmersmann** [ranking-agent/ranking-agent.github.io#19]
An automated testing plan to verify service availability and basic knowledge retrieval has been developed for each Translator tool, with detailed documentation on the expected results of each test.

**Comment by mmersmann** [comment]
**Next Steps:**
1. document code level tests
2. think about service availability (Strider and ARAGORN services to be hosted by NCATS)
3. clarify requirements with deployment WG/Mark Williams

Note: Uptime testing should be handled centrally.

**Comment by mmersmann** [comment]
Code-level tests to be documented in repos (or wikis, depending on what NCATS wants). Note that some of this will be impacted by team meeting with ITRB.

**Action:** @patrickkwang to put this documentation together for Strider, ARAGORN ARA, Transpiler, Answer Coalescence, Ranker, Automat

**Comment by mmersmann** [comment]
**Update:** Finished for Strider

@patrickkwang to finish for Transpiler
@cbizon for Answer Coalescence, Ranker, ARAGORN ARA (blurb on manual testing procedures)
Yaphet for Automat

**Comment by mmersmann** [comment]
Transpiler still in progress

**Automat**
[Unit Tests](https://github.com/RENCI-AUTOMAT/Automat-server/tree/plater-trapi-1.1-comp/Automat/automat/tests)
[Automated Tests](https://github.com/RENCI-AUTOMAT/Automat-server/blob/master/Automat/automat/tests/README.md)

[ARAGORN ARA](https://github.com/ranking-agent/aragorn/blob/main/tests/README.md)
[Answer Coalescence](https://github.com/ranking-agent/AnswerCoalesce/blob/master/tests/README.md)
[ARAGORN Ranker](https://github.com/ranking-agent/aragorn-ranker/blob/master/tests/README.md)

**Comment by patrickkwang** [comment]
Finished for transpiler.
