### ISSUE TITLE
TRAPI v1.1 Compliance

### ISSUE THREAD

**Issue by mmersmann** [ranking-agent/ranking-agent.github.io#21]
Note that TRAPI 1.0 and 1.1 should be up in parallel for the time being. 1.0 will be deprecated at a later date.

**Comment by mmersmann** [comment]
**Next Steps:**
1. Update pydantic models (Patrick)

**Comment by mmersmann** [comment]
**Update:** Pydantic models exist, may be tweaked slightly; Reasoner Transpiler updated; working on Strider (ETA early next week)

**Work remaining:** Automat; Answer Coalescer; ARAGORN; ARAGORN Ranker

**Comment by mmersmann** [comment]
**Update:** Strider master branch is TRAPI 1.1

**Comment by mmersmann** [comment]
**Updates:** 
1. Yaphet working on updates for Automat, should be ready early next week
2. Phil to begin working on ARAGORN, ARAGORN Ranker, Answer Coalescer

**Comment by mmersmann** [comment]
**Updates:**
1. Automat, Strider, Answer Coalescer, Node Normalization in good shape/complete
2. ARAGORN, ARAGORN Ranker will be finished hopefully today (Phil)

**Decision:** Yaphet, Phil, and Patrick will register the 1.1 tools they’ve upgraded with SmartAPI.

**Comment by mmersmann** [comment]
**Decision from 5/21:** register only ARAGORN in ARS and SmartAPI; with Answer Coalesce, and option to turn it off.

@PhillipsOwen to complete registration.

**Comment by PhillipsOwen** [comment]
this is complete and deployed

**Comment by mmersmann** [comment]
**1.0 Updates:** Phil has removed all 1.0 endpoints for ARAGORN
