### ISSUE TITLE
All deployments need to be transitioned over to the new Sterling k8s cluster

### ISSUE THREAD

**Issue by richakanwar13** [ranking-agent/ranking-agent.github.io#47]

**Comment by PhillipsOwen** [comment]
AUTOMAT-plater and Node normalization apps have transitioned to Sterling as production instances. most other deployments are running on Sterling but have not had their ingresses changed to represent the production endpoint

we need to develop a list of what remains to checklist transitioning the rest.

**Comment by PhillipsOwen** [comment]
i went through all the deployments on mitchell/sterling.
 - -dev deployments running in the sterling translator namespce (prod) were moved to sterling/translator-dev namespace.
 -  remaining mitchell deploys for name-res, filter-top-n and aragorn (and friends) were promoted to sterling production.
 -  sterling/aragorn-dev (and friends) where promoted to sterling production.
 
 I am working with Yaphet to determine what to do about the remaining 5-6 apps left on mitchell.

**Comment by PhillipsOwen** [comment]
the following apps remain on mitchell:
 - chem norm
 - onto-bio-names
 - question-rewrite
 - smartbag-bicluster
 - smartbag-ctd (obsolete?)
 - smartbag-foodb (obsolete?)
 - smartbag-gtex (obsolete?)
 - tranql (backend-deployment, backplane-cache, frontend-deployment, frontend-cache)

**Comment by richakanwar13** [comment]
Not to be moved over to Sterling:

chem norm
onto-bio-names
question-rewrite

**Comment by richakanwar13** [comment]
Complete as of 2/25
